version: '3.1'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: etno
      MYSQL_ROOT_PASSWORD: etno
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./database/db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
